### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by tolgacangoz**
Hi @TimothyAlexisVass, thanks for this great blog post! Shouldn't this be like that?

### CODE REVIEW

**Review by TimothyAlexisVass — COMMENTED** [review]
It's a clever suggestion but the text only refers to the actual number of pixels, not their specific channels.

**Comment by tolgacangoz** [comment]
I couldn't understand, can you elaborate?

**Comment by TimothyAlexisVass** [comment]
In the pixel space, there are 1024 × 1024 pixels (px), each with the 3 channels red, green and blue.
In the SDXL latent space, there are 128 × 128 px, each with the 4 channels which SDXL uses.

**Comment by tolgacangoz** [comment]
Yes, and doesn't it mean 3x1024x1024 / 4x128x128 = 48 times compression?

**Comment by TimothyAlexisVass** [comment]
The information for 8×8 pixels with 3 channels is converted into 1×1 pixels with 4 channels.

The channels have absolutely nothing to do with the number of pixels in that regard.

So you can simply think that somehow the information of 64 (8×8) pixels needs to be compressed into 1 (1×1).

Something similar happens with JPEG and MPEG-4 compression too.
You can look at a video about that here:
https://www.youtube.com/watch?v=0me3guauqOU

**Pull request closed without merging**
